remote_theme: pmarsceill/just-the-docs
# color_scheme: dark
baseurl: /doc-bcx-aurelia-dnd
search_enabled: true
title: bcx-aurelia-dnd
aux_links:
  bcx-aurelia-dnd:
    - "//github.com/buttonwoodcx/bcx-aurelia-dnd"
  bcx-aurelia-reorderable-repeat:
    - "//github.com/buttonwoodcx/bcx-aurelia-reorderable-repeat"